### PR TITLE
Bugfix and some new ui

### PR DESCRIPTION
**Pull request by 7408647n**
- Fix a bug, why I can't build the app
- Add the LogOut-button in settings
- Add Appearance-menu in the new Settings-menu
- Add Credits-menu in the new Settings-menu
- Add Debug-menu in the new Settings-menu

### CODE REVIEW

**Comment by cryptoAlgorithm** [comment]
Hi, thanks for the contribution. Could you clarify regarding the bug, preventing you from building the app, that you fixed? I'd like to find out more as I cannot seem to find it from the changes you've made.

**Comment by cryptoAlgorithm** [comment]
Looks good! I'll be adding my own UI touch-ups to this commit as well, before merging it.

**Comment by cryptoAlgorithm** [comment]
@7408647n I've implemented many of these (but in a slightly different place and with different methods) in the `settings` branch, and as such I will be closing this PR (since there are now too many conflicts to merge).

Here are some screenshots of the implementations: (I have decided not to include a sign out button as that required duplicating a lot of existing code)

### Appearance
Screenshot 2023-05-10 at 2 16 44 PM

### Credits
Screenshot 2023-05-10 at 2 18 29 PM

### Debug
Screenshot 2023-05-10 at 2 19 04 PM

**Comment by 7408647n** [comment]
Has the logout button also been added in the settings?
If not, I would fix the merge conflicts

**Comment by cryptoAlgorithm** [comment]
Nope, I decided not to add it because it leads to duplicate code. I might have to refactor the account manager to avoid that.

**Pull request closed without merging**
