### PR TITLE
Re-Intent ISOTimestamp.toDate

### PR DESCRIPTION
**Pull request by Marvae**
Re-intent the method.

### CODE REVIEW

**Comment by cryptoAlgorithm** [comment]
Hey, thanks for the contribution. However, I do not see any change to the method header, it looks like you've just removed and added the definition?

**Comment by Marvae** [comment]
> Hey, thanks for the contribution. However, I do not see any change to the method header, it looks like you've just removed and added the definition?

@cryptoAlgorithm I just rearranged the spaces at the beginning of the method, its intent level is wrong. Maybe the project needs to add some lint tool like swiftLint to enforce Swift style?

**Comment by cryptoAlgorithm** [comment]
image

It looks fine to me...

**Comment by cryptoAlgorithm** [comment]
Or is it one space off 🤔

**Comment by Marvae** [comment]
Weird. You can the file changes. There may be some local settings
Screen Shot 2022-05-26 at 17 57 05

**Comment by cryptoAlgorithm** [comment]
Screenshot 2022-05-26 at 5 59 49 PM

Haha it looks the same to me, which is why I asked

**Comment by Marvae** [comment]
😯Is it a Github bug? So interesting. On my device, the intent looks a bit more cluttered. It seems that the lint tool is the better choice
Screen Shot 2022-05-26 at 18 04 26

**Comment by Marvae** [comment]
NVM. We can ignore this PR. Do you want to use SwiftLint? I can try to help if needed

**Comment by cryptoAlgorithm** [comment]
Thanks for offering the help, but @Candygoblen123 is already working on that. You could still help if you wanted too, so SwiftLint can be enabled sooner xD

**Comment by Marvae** [comment]
Good to know. Thanks!

**Comment by cryptoAlgorithm** [comment]
No issue! any contributions are welcome :)

**Comment by Candygoblen123** [comment]
> NVM. We can ignore this PR. Do you want to use SwiftLint? I can try to help if needed

Since you're here, what SwiftLint rules do you recommend, besides the default?

**Pull request closed without merging**
