### PR TITLE
Hide edit context button on non-owned messages

### PR DESCRIPTION
**Pull request by DanielleMaywood**
Hides the "Edit" button in the context menu for messages sent by anyone other than the current user.

### CODE REVIEW

**Comment by cryptoAlgorithm** [comment]
Thanks for your contribution. The commits look good, but have you done performance testing? I'm worried the extra environment object has a significant CPU/memory impact, especially for longer chats.

**Comment by DanielleMaywood** [comment]
> Thanks for your contribution. The commits look good, but have you done performance testing? I'm worried the extra environment object has a significant CPU/memory impact, especially for longer chats.

I haven't but I can do some later today and post the results.

**Comment by cryptoAlgorithm** [comment]
Thanks. Check the scrolling performance especially for longer channels.

**Comment by DanielleMaywood** [comment]
The following are from me testing on my M1 Macbook Air on MacoS Ventura.

Performance profile from before changes:
SCR-20220819-i6p

Performanc profile from after changes:
SCR-20220819-i6w

Anecdotally, the smoothness of scrolling through channels with lots of messages feels the same to me.

**Comment by cryptoAlgorithm** [comment]
Lmao, it looks like performance actually improved xD. Ok, I'm merging this PR.

**Pull request merged**
